name: hrrr
channels:
  - defaults
  - conda-forge
dependencies:
  - cartopy
  - xarray
  - zarr
  - netcdf4
  - bokeh  
  - datashader
  - holoviews=1.12.1  
  - geoviews
  - hvplot  
  - panel
  - intake
  - intake-xarray
  - metpy
  - pip
  - pip:
    - git+https://github.com/intake/xrviz.git
