name: hrrr
channels:
  - conda-forge
dependencies:
  - geoviews
  - datashader
  - holoviews=1.12.1
  - panel
  - param
  - bokeh
  - hvplot
  - pip
  - pip:
    - git+https://github.com/intake/xrviz.git
